# Generated by Django 5.2 on 2025-04-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdetails',
            name='life_path_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birthdetails',
            name='zodiac_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
